<?php /* Smarty version 2.6.16, created on 2011-07-05 23:41:37
         compiled from C:%5Cwamp%5Cwww%5Cproject%5Cactivecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'title', 'C:\\wamp\\www\\project\\activecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl', 1, false),array('block', 'lang', 'C:\\wamp\\www\\project\\activecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl', 1, false),array('block', 'add_bread_crumb', 'C:\\wamp\\www\\project\\activecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl', 2, false),array('block', 'form', 'C:\\wamp\\www\\project\\activecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl', 4, false),array('block', 'wrap_buttons', 'C:\\wamp\\www\\project\\activecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl', 21, false),array('block', 'submit', 'C:\\wamp\\www\\project\\activecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl', 22, false),array('function', 'cycle', 'C:\\wamp\\www\\project\\activecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl', 13, false),array('function', 'image_url', 'C:\\wamp\\www\\project\\activecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl', 15, false),array('function', 'text_field', 'C:\\wamp\\www\\project\\activecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl', 16, false),array('modifier', 'clean', 'C:\\wamp\\www\\project\\activecollab/application/modules/system/views/languages_admin/edit_translation_file.tpl', 14, false),)), $this); ?>
<?php $this->_tag_stack[] = array('title', array('not_lang' => true)); $_block_repeat=true;smarty_block_title($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start();  $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Edit Translation File<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>: <?php echo $this->_tpl_vars['translation_file'];  $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_title($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack);  $this->_tag_stack[] = array('add_bread_crumb', array('not_lang' => true)); $_block_repeat=true;smarty_block_add_bread_crumb($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start();  $this->_tag_stack[] = array('lang', array('translation_file' => $this->_tpl_vars['translation_file'])); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Edit Translation File<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack);  $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_add_bread_crumb($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>

<?php $this->_tag_stack[] = array('form', array('action' => $this->_tpl_vars['form_url'],'method' => 'post','ask_on_leave' => true)); $_block_repeat=true;smarty_block_form($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
<table class="common_table lang_table">
  <tr>
    <th><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Dictionary Word/Sentence<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></th>
    <th></th>
    <th class="input_column"><?php $this->_tag_stack[] = array('lang', array()); $_block_repeat=true;smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Translated Word/Sentence<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_lang($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?></th>
  </tr>
<?php if (is_foreachable ( $this->_tpl_vars['prepared_form_data'] )): ?>
  <?php $_from = $this->_tpl_vars['prepared_form_data']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['prepared_form_data_key'] => $this->_tpl_vars['prepared_form_data_value']):
?>
  <tr class='<?php echo smarty_function_cycle(array('values' => "odd,even"), $this);?>
'>
    <td class="dictionary"><?php echo ((is_array($_tmp=$this->_tpl_vars['prepared_form_data_value']['dictionary_value'])) ? $this->_run_mod_handler('clean', true, $_tmp) : smarty_modifier_clean($_tmp)); ?>
</td>
    <td class="copy_arrow"><img src="<?php echo smarty_function_image_url(array('name' => 'copy_right.gif'), $this);?>
" alt="copy" /></td>
    <td class="input<?php if (! $this->_tpl_vars['prepared_form_data_value']['translated_value']): ?> new<?php endif; ?>"><?php echo smarty_function_text_field(array('name' => "form_data[".($this->_tpl_vars['prepared_form_data_key'])."]",'value' => $this->_tpl_vars['prepared_form_data_value']['translated_value']), $this);?>
</td>
  </tr>
  <?php endforeach; endif; unset($_from);  endif; ?>
</table>
<?php $this->_tag_stack[] = array('wrap_buttons', array()); $_block_repeat=true;smarty_block_wrap_buttons($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
  <?php $this->_tag_stack[] = array('submit', array()); $_block_repeat=true;smarty_block_submit($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Submit<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_submit($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack);  $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_wrap_buttons($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack);  $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_form($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>