<?php /* Smarty version 2.6.16, created on 2011-07-06 17:32:49
         compiled from /home/mensajes/public_html/gestion/activecollab/application/modules/system/views/roles_admin/_project_role.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'wrap', '/home/mensajes/public_html/gestion/activecollab/application/modules/system/views/roles_admin/_project_role.tpl', 1, false),array('block', 'label', '/home/mensajes/public_html/gestion/activecollab/application/modules/system/views/roles_admin/_project_role.tpl', 2, false),array('function', 'text_field', '/home/mensajes/public_html/gestion/activecollab/application/modules/system/views/roles_admin/_project_role.tpl', 3, false),array('function', 'select_project_permissions', '/home/mensajes/public_html/gestion/activecollab/application/modules/system/views/roles_admin/_project_role.tpl', 7, false),)), $this); ?>
<?php $this->_tag_stack[] = array('wrap', array('field' => 'name')); $_block_repeat=true;smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
  <?php $this->_tag_stack[] = array('label', array('for' => 'roleName','required' => true)); $_block_repeat=true;smarty_block_label($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Name<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_label($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
  <?php echo smarty_function_text_field(array('name' => "role[name]",'value' => $this->_tpl_vars['role_data']['name'],'id' => 'roleName'), $this);?>

<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>

<?php $this->_tag_stack[] = array('wrap', array('field' => 'permissions')); $_block_repeat=true;smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
  <?php echo smarty_function_select_project_permissions(array('name' => "role[permissions]",'value' => $this->_tpl_vars['role_data']['permissions']), $this);?>

<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_wrap($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>