<?php return array (
  'Full description' => 'Descripción completa',
  'New Checklist' => 'Nueva lista de tareas',
  'Completed Checklists' => 'Listas de tareas completadas',
  ':open open tasks of :total tasks in the list' => ':open tareas abiertas de un total de :total en la lista',
  'There are no active checklists here' => 'No hay listas de tareas activas aquí',
  'Edit checklist' => 'Editar lista de tareas',
  'Checklists' => 'Listas de tareas',
  'Active Checklist' => 'Lista de tareas activa',
  'There are no active checklists in this project' => 'No hay listas de tareas activas en este proyecto',
  'Completed Checklist' => 'Lista de tareas completada',
  'Checklist' => 'Lista de tareas',
  'Active Checklists' => 'Listas de tareas activas',
  ':open_count open tasks of :total_count tasks in list' => ':open_count tareas abiertas de :total_count tareas en la lista',
  'Assignees for Tasks' => 'Asignaciones de tareas',
  'Checklists <a href=":url">:name</a> has been created' => 'Las listas de tareas <a href=":url">:name</a> han sido creadas',
  'Set Milestone' => 'Establecer hito',
  'Set Visibility' => 'Establecer visibilidad',
  'Open' => 'Abierto',
  'Description for this checklist is not provided' => 'No se ha indicado una descripción para esta lista de tareas',
  'About Checklists' => 'Acerca de las listas de tareas',
  'Lists of Tasks' => 'Listas de tareas',
  'Checklist is a list of tasks that need to be done in order to get a checklist completed. When all tasks in the checklist are completed, the checklist is completed automatically. Every task in a list can have priority, due date and multiple assignees' => 'La lista de tareas es una lista de tareas que necesitan ser realizadas para completar una lista de tareas. Cuando todas las tareas de una lista de tareas se completen, la lista de tareas se completa automáticamente. Cada tarea en una lista puede tener prioridad, fecha de fin y múltiples personas asignadas',
  'Subscribe to checklist tasks to receive email notification when tasks are completed or reopened' => 'Suscríbete a las tareas de la lista de tareas para recibir notificaciones de correo electrónico cuando las tareas se completen o se reabran',
  'Adds simple task lists to projects' => 'Añade una simple lista de tareas a todos los proyectos',
  'Module will be deactivated and all checklists from all projects will be deleted' => 'El módulo será desactivado y todas las listas de tareas de todos los proyectos serán borradas',
  'Checklist :name has been added' => 'La lista de tareas :name ha sido añadida',
  'Checklist :name has been updated' => 'La lista de tareas :name ha sido actualizada',
  'Exporting checklists data...' => 'Exportando datos de la lista de tareas...',
  'Checklist summary is required' => 'Se requiere el resumen de la lista de tareas',
) ?>