<?php return array (
  'No tasks here' => 'No hay tareas aquí',
  'Calendar' => 'Calendario',
  'Enables viewing project data in a calendar. Global calendar is available plus a calendar for each project and user' => 'Habilita ver datos de proyecto en el calendario. Calendario global está disponible más un calendario para cada proyecto y usuario',
  'Module will be deactivated. Data that is shown in the calendars will not be deleted' => 'El módulo será desactivado. La información mostrada en los calendarios no será eliminada',
  ':user\'s calendar' => 'Calendario de :user',
  'Schedule' => 'Planificar',
  'Sunday' => 'Domingo',
  'Monday' => 'Lunes',
  'Tuesday ' => 'Martes',
  'Wednesday' => 'Miércoles',
  'Thursday' => 'Jueves',
  'Friday' => 'Viernes',
  'Saturday' => 'Sábado',
  'Tickets' => 'Tickets',
) ?>