<?php return array (
  'About Files' => 'Acerca de archivos',
  'Upload Files, File Revisions and Collaborate' => 'Transfiere archivos, revisión de archivos y colaboración',
  'Use Files section to upload files, discuss them, upload and compare versions and more. You can upload and track versions of any file. Files attached to objects in other sections of project are also listed here' => 'Utiliza la sección de archivos para transferir archivos, discutirlos, transferirlos y comparar versiones y más. Puedes transferir archivos y realizar un seguimiento de versiones de un archivo. Los archivos adjuntados a objetos en otras secciones de un proyecto también se listan aquí',
  'Organize in Categories and Associate with Milestones' => 'Organizar en categorías y asociar con hitos',
  'Files can be sorted in categories and associated with milestones; both relations are optional. Filter files by category using the tabs on the right' => 'Los archivos pueden ser ordenados en categorías y asociados con hitos; ambas relaciones son opcionales. Filtra los archivos por categoría utilizando las pestañas de la derecha',
  'Have a Discussion with your Team or Clients' => 'Mantén una discusión con tu equipo o clientes',
  'Post an unlimited number of comments. Use them to discuss file and file revisions with your colleagues and clients' => 'Publica un número ilimitado de comentarios. Utilizalos para discutir acerca de archivos y revisiones de archivos con tus colegas y clientes',
  'Subscribe to a file to receive email notification when new revision is uploaded or new comment is posted. The Person who uploaded the file can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)' => 'Suscríbete a un archivo para recibir notificaciones por email cuando una nueva versión o comentario son enviados. La persona que creó la página puede editar la lista de suscritores usando la herramienta de administración de suscritos (disponible en el menú Opciones)',
  'Older Versions' => 'Versiones más antiguas',
  'Delete Permanently' => 'Eliminar permanentemente',
  'Page :page' => 'Página :page',
  'Thumbnail' => 'Miniatura',
  'File Details' => 'Detalles de archivo',
  'File' => 'Archivo',
  'Attached To' => 'Adjuntado a',
  'Download' => 'Descargar',
  'There are no files in this category' => 'No hay archivos en esta categoría',
  'Upload now' => '¿Subir ahora',
  'There are no files to show' => 'No hay archivos a mostrar',
  'All Files' => 'Todos los archivos',
  'All Attachments' => 'Todos los adjuntos',
  'Manage Categories' => 'Gestionar categorías',
  'Edit File Details' => 'Editar detalles de archivo',
  'Category' => 'Categoría',
  'Files' => 'Archivos',
  'There are no files on this page' => 'No hay archivos en esta página',
  'Latest Version' => 'Última versión',
  'This has no revisions' => 'No tiene revisiones',
  'First Version' => 'Primera versión',
  'New Version' => 'Nueva versión',
  'Move To Trash' => 'Mover a la papelera',
  'Move To Category' => 'Mover a la categoría',
  '<None>' => '<Ninguno>',
  'Select File' => 'Seleccionar archivo',
  'You are about to upload new version of <a href=":url">":name"</a> file. Older versions of this file will not be deleted but saved for future reference' => 'Estás a punto de transferir una nueva versión del archivo <a href=":url">":name"</a>. Las versiones anteriores de este archivo no serán eliminadas, sino salvadas para futuras referencias',
  'Notify People' => 'Notificar a personas',
  'File <a href=":url">:name</a> has been created' => 'El archivo <a href=":url">:name</a> ha sido creado',
  'Set Milestone and Category' => 'Establecer hito y categoría',
  'Set Category' => 'Establecer categoría',
  'Set Visibility' => 'Establecer visibilida',
  'Upload Files' => 'Subir archivos',
  'Description <i>(optional)</i>' => 'Descripción <i>(opcional)</i>',
  'Add Another File' => 'Añadir otro archivo',
  '<strong>Note</strong>: Max upload size is :max_size per file' => '<strong>Nota</strong>: El máximo tamaño de subida es :max_size per file',
  'Upload' => 'Subir',
  'File Name' => 'Nombre de archivo',
  'Image preview. <a href=":url">Click to download</a> full size image' => 'Vista previa de imagen. <a href=":url">Click para descargar</a> la imagen a tamaño completo',
  'Description for this file is not provided' => 'No se ha proporcionado una descripción de este archivo.',
  'Invalid file - last revision was not found' => 'Archivo inválido - no se ha encontrado la última revisión',
  'Please select what you want to do with selected tickets' => 'Porfavor selecciona que quieres hacer con los tickets seleccionados',
  'Please select files that you would like to update' => 'Porfavor selecciona los archivos que quieres actualizar',
  'File ":name" has been updated' => 'El archivo ":name" ha sido actualizado',
  'You haven\\' => 'No has',
  'File not uploaded' => 'Archivo no transferido',
  ':count attachments deleted' => ':count adjuntos eliminados',
  ':count files moved to trash' => ':count archivos movidos a la papelera',
  ':count files updated' => ':count archivos actualizados',
  'Adds file repository to each project. Highlights: files support versioning, can have comments, email notifications, can be organized in categories and more...' => 'Añade repositorio de archivos para cada proyecto. Destacado: soporte de versiones de archivos, pueden tener comentarios, notificaciones por correo electrónico, pueden ser organizados en categorías y más...',
  'Module will be deactivated. All files created with this module will be deleted. Files attached to objects in other modules (tickets, comments etc) will not be deleted' => 'El módulo será desactivado. Todos los archivos creados con este módulo serán eliminados. Los archivos adjuntados a otros objetos en otros módulos (tickets, comentarios, etc.) no serán eliminados',
  'File categories' => 'Categorías de archivo',
  'Exporting files data...' => 'Exportando datos de archivos...',
  '<a href=":user_url">:user_name</a> uploaded a new file' => '<a href=":user_url">:user_name</a> subió un nuevo archivo',
  '<a href=":user_url">:user_name</a> uploaded a new version of <a href=":url">:name</a> file' => '<a href=":user_url">:user_name</a> subió una nueva versión del archivo <a href=":url">:name</a>',
  'File name is required' => 'Se requiere el nombre del archivo',
  'All revision moved to Trash' => 'Todas las revisiones movidas a la papelera',
  'Upload <a href=":upload_url">more files</a> or go back to <a href=":files_url">Files</a> section' => 'Subir <a href=":upload_url">más archivos</a> o volver atrás a la sección de <a href=":files_url">Archivos</a>',
  'Uploading files' => 'Transfiriendo archivos',
  'Done, :files_uploaded files uploaded and :files_failed uploads failed<br />' => 'Hecho, :files_uploaded archivos transferidos correctamente y :files_failed con errores<br />',
  'Done, :files_uploaded files uploaded<br />' => 'Hecho, :files_uploaded archivos transferidos correctamente<br />',
  'Done, :files_failed uploads failed<br />' => 'Hecho, :files_failed transferencias con errores<br />',
) ?>