<?php return array (
  'Submit Ticket / :company' => 'Enviar ticket / :company',
  'Submit Ticket' => 'Enviar ticket',
  'Your Email Address' => 'Tu dirección de correo electrónico',
  'Your Name' => 'Tu nombre',
  'Category' => 'Categoría',
  'Full Description' => 'Descripción completa',
  'Type the code shown' => 'Escribe el código mostrado',
  'Public Submit Settings' => 'Configuración Public Submit',
  'Project for tickets:' => 'Proyecto para tickets:',
  'Enable captcha:' => 'Habilitar captcha:',
  'Enable public submit:' => 'Habilitar public submit',
  'When enabled, Public Submit module will let people submit tickets through a form on your website without having to be a registered and logged in the system. This module is great for receiving support requests or getting feedback from users' => 'Cuando está habilitado, el módulo Public Submit permitirá que la gente pueda enviar tickets a través de un formulario en tu sitio web sin tener que estar registrado e identificado en el sistema. Este módulo es fantástico para recibir peticiones de ayuda o obtener opiniones de los usuarios',
  'Public Submit is <strong>enabled</strong>' => 'Public Submit está <strong>activado</strong>',
  'Submission form is located here: <a href=":url" target="_blank">:url</a>' => 'El formulario de envío está aquí: <a href=":url" target="_blank">:url</a>',
  'After user submits data, a new ticket is created in <a href=":url">:project_name</a> project.' => 'Después de que el usuario envíe la información, se crea un nuevo ticket en el proyecto <a href=":url">:project_name</a>',
  'You need to specify default project for newly created tickets first.' => 'Es necesario especificar el proyecto por defecto para los tickets recién creados',
  'GD Library with FreeType2 is required for captcha protection. <a href=":gd_url">Read more about GD Library</a>' => 'Se requiere la librería GD con FreeType2 para la protección captcha. <a href=":gd_url">Lee más acerca de la librería GD</a>',
  'Public Submit is <strong>disabled</strong>' => 'Public Submit está <strong>desactivado</strong>',
  'GD Library is required for captcha protection. <a href=":gd_url">Read more about GD Library</a>' => 'Se requiere la librería GD para la protección captcha. <a href="gd:url">Lee más acerca de la librería GD</a>',
  'Public Submit' => 'Public Submit',
  'Public Submit settings have been updated' => 'La configuración de Public Submit ha sido actualizada',
  'Code you entered is not valid' => 'El código introducido no es válido',
  'Information about Public Submit module' => 'Información acerca del módulo Public Submit',
  'Submit tickets without having an activeCollab account' => 'Envia tickets sin tener una cuenta de activeCollab',
  'Module will be deactivated. Data you create using this module will not be deleted' => 'El módulo será desactivado. Datos que hayas creado usando este módulo no serán eliminados.',
) ?>