<?php return array (
  'Notify People' => 'Notificar personas',
  'Category' => 'Categoría',
  'Add discussion' => 'Añadir discusión',
  'New Discussion' => 'Nueva discusión',
  'Update Discussion' => 'Actualizar discusión',
  'Discussions' => 'Discusiones',
  'There are no discussions on this page' => 'No hay discusiones en esta página',
  'Discussion' => 'Discusión',
  'Replies' => 'Respuestas',
  'Last Reply' => 'Última respuesta',
  'by <a href=":user_url">:user_name</a>' => 'por <a href=":user_url">:user_name</a>',
  'No discussions in this category' => 'No hay discusiones en esta categoría',
  'Start one now' => '¿Empezar una ahora',
  'No discussions here' => 'No hay discusiones',
  'All Discussions' => 'Todas las discusiones',
  'Manage Categories' => 'Gestionar categorías',
  'Discussion <a href=":url">:name</a> has been created' => 'La discusión <a href=":url">:name</a> ha sido creada',
  'Set Milestone and Category' => 'Establecer hito y categoría',
  'Set Category' => 'Establecer categoría',
  'Set Visibility' => 'Establecer visibilidad',
  'Page :page' => 'Página :page',
  'About Discussions' => 'Acerca de las discusiones',
  'Just Like Online Forums' => 'Como otros foros online',
  'Discussions let you create a number of topics and discuss them with your team and clients. It works just like online forums - system will tell you when there are new messages in a topic and discussions with most recent comments are listed on top' => 'Las discusiones te permiten crear un número de temas y discutirlos con tu equipo y clientes. Funciona como un sistema de foros online - el sistema de avisará cuando haya nuevos mensajes en un tema y las discusiones con los comentarios más recientes se situarán en la parte superior',
  'Organize in Categories and Associate with Milestones' => 'Organizar en categorías y asociar con hitos',
  'Discussions can be sorted in categories and associated with milestones; both relations are optional. Filter discussions by category using the tabs on the right' => 'Las discusiones pueden ordenarse en categorías y asociarlas a hitos; las dos relaciones son opcionales. Filtra las discusiones por categoría utilizando las pestañas de la derecha',
  'Attach Unlimited Number of Files' => 'Adjuntar número ilimitado de archivos',
  'Every discussion message can have an unlimited number of attachments. System will use icons for various file types and thumbnails for images' => 'Cada mensaje de una discusión puede tener un número ilimitado de adjuntos. El sistema utilizará iconos para los tipos de archivo y capturas para las imágenes',
  'Subscribe to a discussion to receive an email notification when new message is posted. Discussion subscribers can be managed using Manage Subscriptions tool (available from Options menu)' => 'Suscríbete a una discusión para recibir una notificación de correo electrónico cuando se publique un nuevo mensaje. Los suscriptores de una discusión pueden ser gestionados utilizando la herramienta de gestión de suscripciones (disponible desde el menú opciones)',
  'Discussion :discussion_name has been started' => 'La discusión :discussion_name ha comenzado',
  'Discussion categories' => 'Categorías de la discusión',
  'Exporting discussions data...' => 'Exportando datos de las discusiones...',
) ?>