<?php return array (
  'About Milestones' => 'Acerca de hitos',
  'Milestones Mark Key Points in a Project' => 'Los hitos establecen puntos clave en un proyecto',
  'Milestones mark key points in a project so you can have a bird-eye view over things that needs to be done, when and who is responsible. Milestone can be a single day event or a time period with start and due date. When you need more details, you can click on a milestone\'s name to "zoom in" and see all related discussions, files and tasks' => 'Los hitos marcan puntos clave en un proyecto, de forma que puedas tener una visón global de las cosas que es necesario hacer, cuando y quién es el responsable de ellas. Los hitos pueden ser un evento en un día concreto o un período de tiempo con un inicio y un fin. Cuando necesites más detalles, puedes hacer click en el nombre del hito para "hacer zoom" sobre él y ver todas las discusiones, archivos y tareas asociadas',
  'Keep Your Calendar Application in Sync with Milestones' => 'Mantén tu aplicación de calendario sincronizada con hitos',
  'If you want to have milestones synchronized with calendars in your favorite calendar application (iCal, Outlook 2007, Google Calendar), then subscribe to iCalendar feed provided by the system. On the Calendar page you can find global feed with milestones and tasks from all active projects. The system also provides a feed for each project and you can find it by visiting overview page of the particular project' => 'Si quieres tener los hitos sincronizados con los calendarios de tu aplicación de calendarios favorita (iCal, Outlook 2007, Google calendar), entonces suscríbete al feed iCalendar proporcionado por el sistema. En la página de calendarios puedes encontrar un feed global con hitos y tareas de todos los proyectos activos. El sistema también proporciona un feed para cada proyecto, y puedes encontrarlo visitando la página de descripción general del proyecto concreto',
  'Email Notifications' => 'Notificaciones de correo electrónico',
  'Subscribe to a milestone to receive email notification when it is completed or reopened. The person responsible for the milestone can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)' => 'Suscríbete a un hito para recibir notificaciones de correo electrónico cuando se complete o se reabra. La persona responsable del hito puede editar la lista de suscriptores utilizando la herramienta de gestión de suscripciones (disponible desde el menú opciones)',
  'Start on' => 'Comienza el',
  'Notes' => 'Notas',
  'New Milestone' => 'Nuevo hito',
  'Completed Milestones' => 'Hitos completados',
  'There are no completed milestones in this project. <a href=":add_url">Create a milestone</a>.' => 'No hay hitos completados en este proyecto. <a href=":add_url">Crear un hito</a>.',
  'Edit Milestone' => 'Editar hito',
  'Milestones' => 'Hitos',
  'Milestone' => 'Hito',
  'Active milestones' => 'Hitos activos',
  'iCalendar' => 'iCalendar',
  'No active milestones here' => 'No hay hitos activos',
  'Would you like to <a href=":add_url">create one</a>' => '¿Quieres <a href=":add_url">crear uno</a>?',
  'Milestone <a href=":url">:name</a> has been created' => 'El hito <a href=":url">:name</a> ha sido creado',
  'Back' => 'Atrás',
  'Reschedule milestone' => 'Replanificar hito',
  'With Successive Milestones' => 'Con hitos sucesivos',
  'Also reschedule all tickets and tasks that belong to milestones you are rescheduling' => 'También reprogramar todos los tickets y tareas que pertenecen a los hitos que estás reprogramando',
  'Reschedule' => 'Replanificar',
  'From / To' => 'De / A',
  'Add to Milestone' => 'Añadir a hito',
  'No notes...' => 'Sin notas...',
  'No tasks in this milestone...' => 'No hay tareas en este hito...',
  'Milestone ":name" has been created' => 'El hito ":name" ha sido creado',
  'Milestone ":name" has been updated' => 'El hito ":name" ha sido actualizado',
  'or' => 'o',
  'You don\\' => 'Tu no',
  '<a href=":url">Click here</a> if you wish to reschedule this milestone' => '<a href=":url">Clic aquí</a> si quieres reprogramar este hito',
  'Exporting milestones data...' => 'Exportando datos de los hitos...',
  'Unknown Milestone' => 'Hito desconocido',
  'This milestone does not have any successive milestones' => 'Este hito no tiene ningún hito sucesivo',
  'Adjust all successive milestone by the same number of days' => 'Ajustar todos los hitos sucesivos con el mismo número de días',
  'Adjust only selected successive milestones by the same number of days' => 'Ajustar sólo los hitos seleccionados con el mismo número de días',
  'Don\'t change anything' => 'No cambiar nada',
  'Add milestones to projects' => 'Añadir hitos a proyectos',
  'Start date is not valid' => 'Fecha de inicio no válido',
  'Due date is not valid' => 'Fecha de vencimiento no válido',
  'Milestone name is required' => 'Se requiere nombre del hito',
  'Start date is required' => 'Se requiere una fecha de inicio',
  'Due date is required' => 'Se requiere una fecha de vencimiento',
  'Start date needs to be before due date' => 'La fecha de inicio debe ser anterior a la fecha de fin',
) ?>